<?php

declare (strict_types=1);
/*
 * This file is part of the Symfony package.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
namespace Symfony\Flex\Command;

use Composer\Command\Base_Command;
use Composer\Config;
use Symfony\Component\Console\Input\Input_Argument;
use Symfony\Component\Console\Input\Input_Interface;
use Symfony\Component\Console\Input\Input_Option;
use Symfony\Component\Console\Output\Output_Interface;
use Symfony\Component\Dotenv\Dotenv;
use Symfony\Flex\Options;
class Dump_Env_Command extends Base_Command
{
    private $config;
    public function __construct(Config $config, private readonly Options $options)
    {
        $this->config = $config;
        parent::__construct();
    }
    protected function configure(): void
    {
        $this->set_name('symfony:dump-env')->set_aliases(['dump-env'])->set_description('Compiles .env files to .env.local.php.')->set_definition([new Input_Argument('env', Input_Argument::OPTIONAL, 'The application environment to dump .env files for - e.g. "prod".')])->add_option('empty', null, Input_Option::VALUE_NONE, 'Ignore the content of .env files');
    }
    protected function execute(Input_Interface $input, Output_Interface $output): int
    {
        $runtime = $this->options->get('runtime') ?? [];
        $env_key = $runtime['env_var_name'] ?? 'APP_ENV';
        if ($env = $input->get_argument('env') ?? $runtime['env'] ?? null) {
            $_SERVER[$env_key] = $env;
        }
        $path = $this->options->get('root-dir') . '/' . ($runtime['dotenv_path'] ?? '.env');
        $GLOBALS['SYMFONY_DOTENV_VARS'] = [];
        if (!$env || !$input->get_option('empty')) {
            $vars = $this->load_env($path, $env, $runtime);
            $env = $vars[$env_key];
        }
        if ($input->get_option('empty')) {
            $vars = [$env_key => $env];
        }
        $vars = var_export($vars, true);
        foreach ($GLOBALS['SYMFONY_DOTENV_VARS'] as $k => $v) {
            $k = var_export($k, true);
            $vars = str_replace($v, "'.(\$_ENV[{$k}] ?? " . (str_starts_with($k, "'HTTP_") ? '' : "\$_SERVER[{$k}] ?? ") . "'').'", $vars);
        }
        unset($GLOBALS['SYMFONY_DOTENV_VARS']);
        $vars = strtr($vars, ["''.(" => '(', ").''.(" => ').(', ").''" => ')']);
        $vars = <<<EOF
        <?php
        
        // This file was generated by running "composer dump-env {$env}"
        
        return {$vars};
        
        EOF;
        file_put_contents($path . '.local.php', $vars, \LOCK_EX);
        $this->get_io()->write_error('Successfully dumped .env files in <info>.env.local.php</>');
        return 0;
    }
    private function load_env(string $path, ?string $env, array $runtime): array
    {
        if (!file_exists($autoload_file = $this->config->get('vendor-dir') . '/autoload.php')) {
            throw new \RuntimeException(\sprintf('Please run "composer install" before running this command: "%s" not found.', $autoload_file));
        }
        require $autoload_file;
        if (!class_exists(Dotenv::class)) {
            throw new \RuntimeException('Please run "composer require symfony/dotenv" to load the ".env" files configuring the application.');
        }
        $env_key = $runtime['env_var_name'] ?? 'APP_ENV';
        $globals_backup = [$_SERVER, $_ENV];
        unset($_SERVER[$env_key]);
        $_ENV = [$env_key => $env];
        $_SERVER['SYMFONY_DOTENV_VARS'] = implode(',', array_keys($_SERVER));
        putenv('SYMFONY_DOTENV_VARS=' . $_SERVER['SYMFONY_DOTENV_VARS']);
        try {
            $dotenv = new Dotenv();
            if (!$env && file_exists($p = "{$path}.local")) {
                $env = $_ENV[$env_key] = $dotenv->parse(file_get_contents($p), $p)[$env_key] ?? null;
            }
            if (!$env) {
                throw new \RuntimeException(\sprintf('Please provide the name of the environment either by passing it as command line argument or by defining the "%s" variable in the ".env.local" file.', $env_key));
            }
            $test_envs = $runtime['test_envs'] ?? ['test'];
            $dotenv->load_env($path, $env_key, 'dev', $test_envs);
            unset($_ENV['SYMFONY_DOTENV_VARS'], $_ENV['SYMFONY_DOTENV_PATH']);
            $env = $_ENV;
        } finally {
            [$_SERVER, $_ENV] = $globals_backup;
        }
        return $env;
    }
}
namespace Symfony\Component\Dotenv;

function getenv(?string $name = null, bool $local_only = false): string|array|false
{
    if (null === $name) {
        return \getenv($name, $local_only);
    }
    return $GLOBALS['SYMFONY_DOTENV_VARS'][$name] ??= md5(random_bytes(10));
}